# Generated by Django 4.1 on 2022-10-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=200, verbose_name='e-mail')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст Записи')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата созадния')),
                ('changed_at', models.DateField(auto_now=True, verbose_name='Дата редактирования')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активная'), ('BLOCKED', 'Заблокировано')], default='ACTIVE', max_length=20, verbose_name='Статус')),
            ],
        ),
    ]
